version: '3'

services:
  db:
    container_name: 'phisanuchai-postgres'
    image: 'postgres:latest'
    ports:
      - 54322:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    image: postgres:14.4
    restart: 'unless-stopped'
    